[project]
name = "lostark-arkgrid-gem-locator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "line-profiler>=5.0.0",
    "pydantic>=2.11.9",
]
